version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Dev1234
      POSTGRES_DB: nestdb
    ports:
      - 5499:5432
